
export default {
    "common": {
        "confidential_warning": "Please do not enter any sensitive data or personally identifiable information (names, surnames). Describe situations in a general way. All data remains solely within the application and is not sent anywhere."
    },
    "header": {
        "back_aria_label": "Back to dashboard"
    },
    "footer": {
        "dedication": "For Marysia and Kuba, with boundless love from Mom. Remember, you are special and can conquer the world. This is a gift so you always feel safe."
    },
    "dashboard": {
        "title": "Welcome to the Support Assistant",
        "description": "Your center for understanding, supporting, and responding to your child's needs. Choose a module to get started.",
        "cards": {
            "geminiKids": { "title": "Gemini Kids", "description": "Chat with Sparky, a friendly robot who is your new friend." },
            "loyaltyProgram": { "title": "Rewards Program", "description": "Collect stickers, take selfies, and unlock family activities for daily successes." },
            "smartwatch": { "title": "Child's Smartwatch", "description": "A virtual watch that helps in difficult moments by providing supportive tasks." },
            "attentionHub": { "title": "Attention Hubs", "description": "A focus zone for children: interactive, sensory activities generated by AI." },
            "assistantConversation": { "title": "Conversation with Assistant", "description": "Talk live with an AI assistant to support communication and interpret the child's needs." },
            "dyadicRegulation": { "title": "Exercises Together", "description": "Strengthen your bond and regulation through joint, interactive exercises with your child." },
            "strategyGuide": { "title": "Strategies & Support", "description": "Get immediate, personalized advice for challenging situations." },
            "escalationMonitor": { "title": "Escalation Monitor", "description": "Identify stages of escalation and receive real-time intervention strategies." },
            "drawingInterpreter": { "title": "Drawing Interpreter", "description": "Interpret your child's drawings to gain insight into their emotional world." },
            "abcLogger": { "title": "ABC Logger", "description": "Log events to analyze antecedents, behaviors, and consequences." },
            "skillBuilder": { "title": "Skill Builder", "description": "Replace challenging behaviors with new, positive ways of communicating." },
            "earlyWarningSystem": { "title": "Early Warning System", "description": "Analyze data to proactively identify risk factors and prevent crises." },
            "realTimeSpeechMonitor": { "title": "Live Speech Monitor", "description": "Analyze speech in real-time for emotional and cognitive indicators." },
            "visualSchedule": { "title": "Visual Schedule", "description": "Generate daily schedules with pictograms to increase predictability." },
            "successJournal": { "title": "Success Journal", "description": "Record and celebrate positive moments, small and large achievements, and progress." },
            "dataAnalytics": { "title": "Analytics & Predictions", "description": "Discover patterns and forecasts using advanced Gemini Pro analysis." },
            "progressTracker": { "title": "My Progress", "description": "Track the child's development path based on collected data and analysis." },
            "speechInterpreter": { "title": "Speech Interpreter", "description": "Record and analyze a child's speech to better understand their intentions." },
            "imageEditor": { "title": "Image Editor", "description": "Edit your photos with text prompts using Gemini." },
            "videoAnalyzer": { "title": "Video Analyzer", "description": "Upload a video and ask questions to understand its content with Gemini Pro." },
            "videoGenerator": { "title": "Video Generator", "description": "Create videos from text or animate images using the Veo model." },
            "localResources": { "title": "Local Resources", "description": "Find specialists and support in your area with Google Maps integration." }
        }
    },
    "progressTracker": {
        "title": "My Progress",
        "description": "Soon you will find visualizations of progress and the child's development path based on collected data here."
    },
    "loyaltyProgram": {
        "title": "Sticker Rewards Program",
        "description": "Collect daily stickers and unlock rewards to celebrate successes big and small!",
        "earn_sticker_button": "Get Today's Sticker!",
        "earning_sticker": "Generating sticker...",
        "sticker_earned_today": "Today's sticker is already earned! Come back tomorrow.",
        "your_stickers": "Your Sticker Collection",
        "print_sticker": "Print",
        "printed_today": "Printed today",
        "family_rewards_title": "Family Rewards",
        "unlock_activity_button": "Unlock a New Activity!",
        "unlocking_activity": "Finding an idea...",
        "collect_more_stickers": "Collect {count} more stickers to unlock!",
        "greetings": {
            "morning": "Good morning!",
            "afternoon": "Good afternoon!",
            "evening": "Good evening!",
            "night": "Good night!"
        },
        "success_calendar_title": "Success Calendar",
        "selfie_corner_title": "Selfie Corner with Parent",
        "take_selfie_button": "Take a Selfie",
        "your_selfies": "Your Moments Together",
        "no_selfies": "You don't have any selfies yet. Time to change that!",
        "days": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        "months": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    }
}
